name: Grype Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true
